swagger: "2.0"
info:
  title: SamsungTV-API
  version: 1.0.0
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /status:
    get:
      description: Checks the configuration and gets the status of the TV
      operationId: getStatus
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/StatusResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"          
  /key/{key}:
    parameters:
      - name: key
        type: string
        in: path
        required: true
    post:
      description: Sends a remote control key to the TV
      operationId: postKey
      responses:
        202:
          description: Accepted
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  StatusResponse:
    type: object
    required:
      - host
      - reachable
    properties:
      host:
        type: string
        description: host name or IP address of the TV
      reachable:
        type: boolean
        description: if the TV is reachable
      tvResponse:
        type: string
        description: the status response from the TV
  ErrorResponse:
    type: string
    